#!/bin/sh

updatedns() {
    if [ "$new_ip_address" = "$old_ip_address" ]; then
        return
    fi
    updatedns
}


case $reason in
    BOUND|RENEW|REBIND|REBOOT)
        updatedns
        ;;
esac
