#!/usr/bin/env python3

import sys
import os
import argparse
import collections
import configparser
import fcntl
import json
import socket
import struct
import time


try:
    import libcloud.dns.providers
    from libcloud.dns.types import Provider, RecordType
except ImportError:
    sys.stderr.write('Missing libcloud package\n')
    sys.exit(-1)


class MultiOrderedDict(dict):
    def __setitem__(self, key, value):
        if isinstance(value, list) and key in self:
            self[key].extend(value)
        else:
            super().__setitem__(key, value)


class UsageError(Exception):
    pass


class UpdateDns:
    def __init__(self, args):
        self.interfaces = collections.defaultdict(list)
        self.drivers    = {}
        self.domains    = {}
        self.records    = {}

        self.verbose = args.verbose

        # get a list of providers that this version of libcloud supports
        libcloud_providers = []
        for provider in dir(Provider):
            if provider.startswith('__'):
                continue
            libcloud_providers.append(provider)

        ini = configparser.ConfigParser(dict_type=MultiOrderedDict, strict=False)
        ini.optionxform = str

        try:
            ok = ini.read(args.ini)
        except configparser.ParsingError as e:
            raise ValueError(str(e)) from None

        if not ok:
            raise ValueError('Could not open ' + args.ini) from None

        for section in ini.sections():
            provider = section.strip().upper()
            hostname = section.strip()

            # check to see if section name is a DNS provider
            if provider in libcloud_providers:
                credentials = dict(ini.items(section))

                domains = credentials.pop('domain', '')
                domains = domains.split('\n')

                Driver = libcloud.dns.providers.get_driver(getattr(Provider, provider))
                driver = Driver(**credentials)
                self.drivers[provider] = driver

                for domain in domains:
                    self.domains[domain] = [driver]

            else:
                host = dict(ini.items(section))
                if 'interface' not in host:
                    print('Missing interface from host', section)
                    continue
                self.interfaces[host['interface']].append(hostname)

        self.enumerate()

        if args.list:
            self.list()
        elif args.monitor:
            self.monitor()
        elif args.delete:
            self.delete(args.delete)
        elif args.name and args.addr:
            self.create(args.name, args.addr)
        elif args.name or args.addr:
            raise ValueError('specify --name and --addr')
        else:
            raise UsageError()

    def _log(self, *args):
        if self.verbose:
            print(*args)

    def enumerate(self):
        for provider,driver in self.drivers.items():
            for zone in driver.list_zones():
                zone_domain = zone.domain
                if zone_domain.endswith('.'):
                    zone_domain = zone_domain[:-1]

                if zone_domain not in self.domains:
                    self._log('Skipping', zone_domain)
                    continue

                self.domains[zone_domain].append(zone)

                for record in driver.list_records(zone):
                    if record.type != 'A':
                        continue
                    domain_name = zone.domain
                    if domain_name.endswith('.'):
                        domain_name = domain_name[:-1]

                    fqdn = domain_name
                    if record.name and record.name != '@':
                        fqdn = record.name + '.' + fqdn

                    self.records[fqdn] = record

    def list(self):
        for fqdn,record in self.records.items():
            print('%-16s %s' % (record.data, fqdn))

    def _find_driver(self, fqdn):
        for zone_domain in self.domains:
            if not fqdn.endswith(zone_domain):
                continue
            driver,zone = self.domains[zone_domain]
            name = fqdn[:-(len(zone_domain)+1)]
            return driver,zone,name

        raise ValueError('Unknown domain:', fqdn)

    def create(self, fqdn, addr):
        driver,zone,name = self._find_driver(fqdn)

        if fqdn in self.records:
            record = self.records[fqdn]
            if addr != record.data:
                self.records[fqdn] = driver.update_record(record, data=addr)
                self._log('Updated:', fqdn, '=', addr)
                return True
            else:
                self._log('No change:', fqdn, '=', addr)
        else:
            self.records[fqdn] = driver.create_record(name, zone, RecordType.A, addr)
            self._log('Created:', fqdn, '=', addr)
            return True

    def delete(self, fqdns):
        for fqdn in fqdns:
            if fqdn not in self.records:
                self._log('Unknown host:', fqdn)
                continue

            driver,zone,name = self._find_driver(fqdn)

            driver.delete_record(self.records[fqdn])
            del self.records[fqdn]
            self._log('Deleted:', fqdn)

    def monitor(self):
        while True:
            for interface,fqdns in self.interfaces.items():
                try:
                    local_address = get_local_address(interface)
                except Exception as e:
                    self._log('Could not get address for interface', interface, ':', e)
                    continue

                for fqdn in fqdns:
                    modified = self.create(fqdn,local_address)
                    if modified:
                        print('Updated:', fqdn, '=', local_address)

            time.sleep(60.0)


def main():
    argparser = argparse.ArgumentParser()

    argparser.add_argument('--name', '-n',
        metavar='<name>',
        help='create or update new DNS entry'
        )

    argparser.add_argument('--addr', '-a',
        metavar='<ip>',
        help='address for new DNS entry'
        )

    argparser.add_argument('--list', '-l',
        action='store_true',
        help='list all zones'
        )

    argparser.add_argument('--monitor', '-m',
        action='store_true',
        help='monitor interfaces for changes'
        )

    argparser.add_argument('--delete', '-d',
        metavar='<name>', nargs='+',
        help='delete DNS entry'
        )

    argparser.add_argument('--ini', '-i',
        metavar='<path>',
        help='ini file to parse'
        )

    argparser.add_argument('--verbose', '-v',
        action='store_true',
        help='enable verbose options'
        )

    args = argparser.parse_args()

    if not args.ini:
        args.ini = os.path.join(os.path.dirname(__file__), 'updatedns.ini')

    try:
        updateDns = UpdateDns(args)
    except UsageError:
        argparser.print_help()
        return -1
    except ValueError as e:
        print('ERROR:', e)
        return -1

    return 0


def get_local_address(ifname):
    SIOCGIFADDR = 0x8915
    skt = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    ifname = ifname[:15].encode('ascii')
    ifname = struct.pack('256s', ifname)
    data = fcntl.ioctl(skt.fileno(), SIOCGIFADDR, ifname)
    return socket.inet_ntoa(data[20:24])


if '__main__' == __name__:
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        pass
